# Generated by Django 3.2.6 on 2023-05-30 15:01

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(help_text='Введите имя (максимум 50 символов)', max_length=50, verbose_name='Имя')),
                ('last_name', models.CharField(help_text='Введите фамилию (максимум 100 символов)', max_length=100, verbose_name='Фамилия ')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(help_text='Введите ваш телефон для связи', max_length=128, region=None, verbose_name='Телефон для связи')),
                ('email', models.EmailField(help_text='Укажите Вашу электронную почту', max_length=254, unique=True, verbose_name='Выша электронная почта')),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin')], default='user', help_text='Выбирите вашу роль', max_length=6, verbose_name='Роль пользователя')),
                ('is_active', models.BooleanField(default=True, help_text='Укажите активен ли аккаунт', verbose_name='Активнасть аккаунта')),
                ('image', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
